# Dockerfile added in both services
version: '3'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - '28018:27017'

  active_mq:
    image: rmohr/activemq:latest
    container_name: activemq
    restart: always
    ports: 
      - '61616:61616'
      - '5672:5672'
      - '61613:61613'
      - '1883:1883'
      - '8161:8161'

  user_dock:
    image: eauction-user-dock:latest
    build: ./E-Auction-User/
    container_name: eauction-user-dock
    restart: always
    ports:
      - '8081:8081'
    depends_on:
      - mongo_db
      - active_mq

  buyer_dock:
    image: eauction-buyer-dock:latest
    build: ./E-Auction-Buyer/
    container_name: eauction-buyer-dock
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - mongo_db
      - active_mq

  seller_dock:
    image: eauction-seller-dock:latest
    build: ./E-Auction-Seller/
    container_name: eauction-seller-dock
    restart: always
    ports:
      - '8083:8083'
    depends_on:
      - mongo_db
