package com.eAuction.eAuction.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.util.Date;

import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;


@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName =  "BID_DATA")
public class BidDto {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotNull
    @DynamoDBAttribute
    private String productId;

    @NotNull
    @DynamoDBAttribute
    private int bidAmount;

    @NotNull
    @DynamoDBAttribute
    private Date bidDate;

    @NotNull
    @DynamoDBAttribute
    private String createdBy;
}
