package com.eAuction.eAuction.dao;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.validation.constraints.NotNull;

@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
@DynamoDBTable(tableName = "USERS")
public class UsersDto {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @NotNull
    @DynamoDBAttribute
    private String firstName;

    @NotNull
    @DynamoDBAttribute
    private String lastName;

    @NotNull
    @DynamoDBAttribute
    private String address;

    @NotNull
    @DynamoDBAttribute
    private String city;

    @NotNull
    @DynamoDBAttribute
    private String state;

    @NotNull
    @DynamoDBAttribute
    private String pin;

    @NotNull
    @DynamoDBAttribute
    private String phone;

    @NotNull
    @DynamoDBAttribute
    private String email;

    @NotNull
    @DynamoDBAttribute
    private String password;

    @NotNull
    @DynamoDBAttribute
    private  String userType;

}